<?php

namespace Bundle\CommonBundle\Entity\Song;

use Bundle\CommonBundle\Entity\BaseEntity;
use Bundle\CommonBundle\Entity\BaseRepository;

/**
 * SongRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SongRepository extends BaseRepository
{
    /** Событие после вставки сущности
     * @param BaseEntity $entity
     */
    protected function prePersist(BaseEntity $entity)
    {
        parent::prePersist($entity);

        $entity->getAuthor()->incrementSongCount();
    }
}
