imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

services:
    fos_user.doctrine_registry:
        alias: doctrine

framework:
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    templating:
        engines: ['twig']
    validation: { enable_annotations: true }

    secret:                 "%secret%"
    default_locale:         "%locale%"
    form:                   ~
    csrf_protection:        ~
    session:
        save_path: %kernel.root_dir%/var/sessions
    fragments:              ~
    translator:             ~
    trusted_proxies:        ~
    http_method_override:   true

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ MainBundle ]
    filters:
        cssrewrite: ~

doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Bundle\CommonBundle\Entity\User

common:
    realplexor:
        url:        %realplexor_url%
        host:       %realplexor_host%
        port:       %realplexor_port%
        namespace:  %realplexor_namespace%