security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    vova: { password: vova_player, roles: [ 'ROLE_ADMIN' ] }
                    oleg:  { password: oleg_rap, roles: [ 'ROLE_USER' ] }
                    valera:  { password: valera_valera, roles: [ 'ROLE_USER' ] }
                    natasha:  { password: natasha_girl, roles: [ 'ROLE_USER' ] }
                    sergei:  { password: sergei_18, roles: [ 'ROLE_USER' ] }
                    alexandr:  { password: alexandr_null, roles: [ 'ROLE_USER' ] }
                    alex:  { password: mrpenis, roles: [ 'ROLE_USER' ] }
                    alex2:  { password: alex_dup, roles: [ 'ROLE_USER' ] }
                    marat:  { password: marat_23, roles: [ 'ROLE_USER' ] }
                    artem:  { password: artem_90, roles: [ 'ROLE_USER' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/admin/login$
            security: false

        work_area:
            pattern:    ^/
            form_login:
                check_path: security_check
                login_path: login
            logout:
                path:   logout

        admin_area:
            pattern:    ^/admin/
            form_login:
                check_path: security_check
                login_path: login
            logout:
                path:   logout
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
