<?php

namespace Bundle\CommonBundle\Entity;

use Bundle\CommonBundle\Entity\BaseEntity;
use Bundle\CommonBundle\Entity\BaseRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends BaseRepository
{
    /** Get top users
     * @return mixed
     */
    public function getTopUsers()
    {
        $query = $this->createQueryBuilder('u');
        $query
            ->setMaxResults(10)
            ->addOrderBy('u.likeReceiveCount', 'DESC');

        return $query->getQuery()->getResult();
    }
}
