<?php

namespace Bundle\CommonBundle\Entity\Room;

use Bundle\CommonBundle\Entity\BaseRepository;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends BaseRepository { }
