services:
#    common.example:
#        class: Bundle\CommonBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    kernel.event_listener.json_request_transformer:
        class: Bundle\CommonBundle\EventListener\JsonRequestTransformerListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }

    drklab.realplexor_instance:
        class: Bundle\CommonBundle\Service\DklabRealplexor
        arguments: [ %realplexor_host%, %realplexor_port%, %realplexor_namespace% ]
        public: false

    drklab.realplexor.manager:
        class: Bundle\CommonBundle\Service\RealplexorManager
        arguments: [ @drklab.realplexor_instance ]