services:
#    common.example:
#        class: Bundle\CommonBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    base.repository:
        class: Bundle\CommonBundle\Entity\BaseRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        calls:
            - [ setContainer, [ '@service_container' ] ]

    song.repository:
        parent: base.repository
        class: Bundle\CommonBundle\Entity\Song\SongRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ CommonBundle:Song\Song ]

    vote.repository:
        parent: base.repository
        class: Bundle\CommonBundle\Entity\Vote\VoteRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ CommonBundle:Vote\Vote ]